<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [2]:
A = [[1,2],[3,4]]
B = [[1,2 ,3, 4, 5],[5 ,6, 7, 8, 9]]
P = [[1,3,4],[2,5,7],[5,9,6]]
Q =  [[1,0,0],[0,1,0],[0,0,1]]

#A,B,P,Q are the lists of lists

def MulMatrix(X,Y):
    #to check if the multiplication is possible
    if len(X[0]) != len(Y):
        return print("Not possible")
    
    #first we construct zero matrix C = A * B of order len(A) X len(B[0])
    C = []
    C_row=len(Y[0])*[0]
    for i in range(len(X)):
        C.append(C_row[:])
    
    for i in range(len(C)): #iterating for rows
        for j in range(len(C[0])): #iterating for column value
            for k in range(0,len(Y)):#the calculation for matrix multiplication of each element
    
               C[i][j] +=  X[i][k] * Y[k][j]
            
    #For output in form of a matrix
    for lst in C:
        print(lst)
    return

MulMatrix(A,B)
MulMatrix(P,Q)
MulMatrix(B,P)

[11, 14, 17, 20, 23]
[23, 30, 37, 44, 51]
[1, 3, 4]
[2, 5, 7]
[5, 9, 6]
Not possible


Reference : https://stackoverflow.com/questions/17870612/printing-a-two-dimensional-array-in-python


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [1]:
import random #random imported for the random selection

def pick_a_number_from_list(A):  #a function defined for the random selection
    # your code here for picking an element from with the probability propotional to its magnitude
    
    #assigning lists & values to be used in program
    ini = 0; weighted = []; cumul=[];n=[];
    
    #to fing the weight of each element
    for element in A:
        weight = element/sum(A)
        weighted.append(weight)
    # to calculate the cumulative weight of elements
    for element in weighted:
        ini+= element
        cumul.append(ini)
    #select an element based on its weight
    for element in cumul:
        rand_select = random.uniform(0.0,1.0) #selects a random no from (0-1)
        if element <= rand_select:
            n.append(element)        
    print(A[len(n)])

def sampling_based_on_magnitude(X): #a function defined to perform the random event 100 times
    for i in range(0,100):
        number = pick_a_number_from_list(A)
    return number 


A = [0,5 ,27 ,6, 13, 28, 100, 45, 10, 79]
sampling_based_on_magnitude(A)

100
100
100
28
28
45
100
28
45
13
100
100
28
100
10
100
45
28
100
10
100
100
100
45
28
100
100
10
45
45
100
45
45
100
100
45
100
100
28
28
100
13
100
45
100
45
45
100
28
100
100
45
100
79
45
45
45
45
10
10
100
28
45
100
100
100
100
45
45
45
45
28
45
28
45
100
100
45
28
45
45
100
45
45
45
100
45
28
100
45
100
10
28
45
28
28
45
13
45
100


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [24]:
A = "234"               
B = "a2b3c4"            
C = "abc"                
D = "#2a$#b%c%561#" 

import re
#importing the re module, which can be used to work with Regular Expressions.
#RegEx can be used to check if a string contains the specified search pattern.

def replace_digits(String):
    
    # using sub in re to replace the non-digits,^ returns except for
    x = re.sub("[^0-9]","",str(String))
    y = re.sub("[0-9]","#",x)  
    return(y)

print(replace_digits(A))
print(replace_digits(B))
print(replace_digits(C))
print(replace_digits(D))

###
###

####


Reference : https://www.w3schools.com/python/python_regex.asp#sub

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [9]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]


def display_dash_board(students, marks):
    file = dict(zip(Students,Marks))
    
    # write code for computing top top 5 students
    print("\ntop_5_students")
    top_5_students = sorted(file.items(), key=lambda item: item[1],reverse=True)[:5]
    for i in top_5_students:
        print(i[0], i[1])
    
    # write code for computing top least 5 students
    print("\nleast_5_students")
    least_5_students = sorted(file.items(), key=lambda item: item[1])[:5]
    for i in least_5_students:
        print(i[0], i[1])
    

    #computing students_within_25_and_75 percentile
    print("\nstudents_within_25_and_75 percentile")
    # first we sort the dictionary in ascending order & then calculate percentiles
    X = sorted(file.items(), key=lambda item: item[1])
    
    max_marks = max(Marks); min_marks = min(Marks)
    diff = max_marks - min_marks
    percentile_25 = diff*0.25; percentile_75 = diff*0.75
    
    for key,value in X:
        percentage = float((value/100) * 100)
        if percentile_25 < percentage < percentile_75:
            print(key,value,percentage)
    return

display_dash_board(Students, Marks)


top_5_students
student8 98
student10 80
student2 78
student5 48
student7 47

least_5_students
student3 12
student4 14
student9 35
student6 43
student1 45

students_within_25_and_75 percentile
student9 35 35.0
student6 43 43.0
student1 45 45.0
student7 47 47.0
student5 48 48.0


Reference :https://careerkarma.com/blog/python-sort-a-dictionary-by-value/

<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [26]:
import math

# here S is list of tuples and P is a tuple ot len=2

def closest_points_to_p(S, P):
    # write your code here
    
    #an empty list is declared first that is to be used to store the cosine distances
    cos_d = []
    for i in range(len(S)):
        d = math.acos((((S[i][0]*P[0])+(S[i][1]*P[1]))/((math.sqrt((S[i][0]**2)+(S[i][1]**2))) *(math.sqrt((P[0]**2)+(P[1]**2))))))
        cos_d.append(d)
        
    #create a dictionary for the distances corresponding to the given points    
    dictionary = dict(zip(S,cos_d))
    
    # we will find the 5 nearest points corresponding to the cos-distances using a lambda function    
    for key, value in sorted(dictionary.items(), key=lambda item: item[1])[:5]:
        print("point:{0} " " | " "distance: {1}".format(key,value))
    return

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

closest_points_to_p(S,P)

point:(6, -7)  | distance: 0.06512516333438509
point:(1, -1)  | distance: 0.14189705460416438
point:(6, 0)  | distance: 0.9272952180016123
point:(-5, -8)  | distance: 1.2021004241368467
point:(-1, -1)  | distance: 1.4288992721907328


Reference :https://careerkarma.com/blog/python-sort-a-dictionary-by-value/

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [27]:
import re

def i_am_the_one(Red,Blue,line):
    #Blank lists to store the calculated value as per the formulae
    Red_S = []
    Blue_S= []
    #iterating over each equation in list of lines
    for eq in line:
        #converting the string value of the lines to float value
        a = [float(s) for s in re.split('x|y',eq)]
        
        #Calculationg as per the formulae ax + by - c
        #For Red points
        R = []
        for i in range(len(Red)):
             S = ((a[0]*Red[i][0]) + (a[1]*Red[i][1]) - a[2]) #ax+by-c formulae
             R.append(S)
        Red_S.append(R)
        
        #For Blue points
        B = []
        for j in range(len(Blue)):
             S = ((a[0]*Blue[i][0]) + (a[1]*Blue[i][1]) - a[2]) #ax+by-c formulae
             B.append(S)
        Blue_S.append(B)
    #To check if line separates the points or not
    #Logic : if both lists of calculated values have different signs they do, else not
    for r in range(len(line)):
        if ((all(i > 0 for i in Red_S[r])) and (all(i < 0 for i in Blue_S[r]))) or ((all(i < 0 for i in Red_S[r])) and (all(i > 0 for i in Blue_S[r]))):
            print("Yes")
        else:
            print("No")

            
Oranges = [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Apples = [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]            


i_am_the_one(Oranges,Apples,Lines)          
            

Yes
No
No
Yes


References:- Logic:FAQ’s of Python Mandatory Assignment(Medium) https://www.w3schools.com/python/python_regex.asp https://www.geeksforgeeks.org/python-check-if-all-elements-in-list-follow-a-condition/

<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [18]:
def curve_smoothing(A):
    
    # to convert a string into a list
    S = A.split(',')
    
    #to find the index of the digits in the given string
    dig_index = []
    for idx in range(len(S)):
        if S[idx].isdigit():
            dig_index.append(idx)
    dig_index.append(len(S)-1)
    # condition for strings following  given 4th condition
    if dig_index[0] > 0 and dig_index[-1] > dig_index[-2]:
        #we'll divide our list to fill from left
        
        start = []
        for i in range(dig_index[0] + 1):
                v  = float(S[dig_index[0]])/ (dig_index[0] + 1)
                start.append(v) 
                
        #moving over to the next digit encountered
        #first element from left to next = middle
        mid = []
        for i in range(dig_index[1] - 1):
            l = (float(start[len(start)-1]) + float(S[dig_index[1]])) / (dig_index[1]-1)
            mid.append(l)
            
        #using our condition for the end blanks/dividing value    
        end = []
        if dig_index[-1] > dig_index[-2]:

            for i in range((dig_index[-1] - dig_index[-2]) + 1 ):
                m = mid[-1]/((dig_index[-1] - dig_index[-2]) + 1 )
                end.append(m)
            del mid [-1]        

        del start[-1];
        S = start+mid+end

    else:
        #the ref to length(string) is deleted
        del dig_index[-1]
        
        k = 0 
        #iterating through the index values stored
        for i in dig_index: 
            k+= float(S[i])
        #digits distribition
        for j in range(len(S)):
            S[j] = k/len(S)

    return S #list of values


M = "_,_,_,24"
N = "40,_,_,_,60"
O = "80,_,_,_,_"
P = "_,_,30,_,_,_,50,_,_"

print(curve_smoothing(M))
print(curve_smoothing(N))
print(curve_smoothing(O))
print(curve_smoothing(P))


[6.0, 6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Conditional probabilities</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [19]:
def compute_conditional_probabilites(A):
    
    #declare initial variables with value zero to store the occurence
    S1 = S2 = S3 = 0;
    F1S1=F2S1=F3S1=F4S1=F5S1=  F1S2=F2S2=F3S2=F4S2=F5S2=  F1S3=F2S3=F3S3=F4S3=F5S3 = 0;
    
    # simply using the conditional probability formulae,we'll store the values of each combination,in accordance to occurence
    
    for i in range(len(A)):
       
        if (A[i][1] == 'S1'):
            S1 += 1
            
            if A[i][0] == 'F1':
                F1S1 += 1
            if A[i][0] == 'F2':
                F2S1 += 1
            elif A[i][0] == 'F3':
                F3S1 += 1
            elif A[i][0] == 'F4':
                F4S1 += 1
            elif A[i][0] == 'F5':
                F5S1 += 1
    
    
        elif (A[i][1] == 'S2'):
            S2 += 1 

            if A[i][0] == 'F1':
                F1S2 += 1
            elif A[i][0] == 'F2':
                F2S2 += 1
            elif A[i][0] == 'F3':
                F3S2 += 1
            elif A[i][0] == 'F4':
                F4S2 += 1
            elif A[i][0] == 'F5':
                F5S2 += 1
    
        else :
            S3 += 1 

            if A[i][0] == 'F1':
                F1S3 += 1
            elif A[i][0] == 'F2':
                F2S3 += 1
            elif A[i][0] == 'F3':
                F3S3 += 1
            elif A[i][0] == 'F4':
                F4S3 += 1
            else:
                F5S3 += 1
            
    print('P(F=F1|S==S1)=',F1S1,'/',S1,', P(F=F1|S==S2)=',F1S2,'/',S2, ', P(F=F1|S==S3)=',F1S3,'/',S3)
    print('P(F=F2|S==S1)=',F2S1,'/',S1,', P(F=F2|S==S2)=',F2S2,'/',S2, ', P(F=F1|S==S3)=',F2S3,'/',S3)
    print('P(F=F3|S==S1)=',F3S1,'/',S1,', P(F=F3|S==S2)=',F3S2,'/',S2, ', P(F=F1|S==S3)=',F3S3,'/',S3)
    print('P(F=F4|S==S1)=',F4S1,'/',S1,', P(F=F4|S==S2)=',F4S2,'/',S2, ', P(F=F1|S==S3)=',F4S3,'/',S3)
    print('P(F=F5|S==S1)=',F5S1,'/',S1,', P(F=F5|S==S2)=',F5S2,'/',S2, ', P(F=F1|S==S3)=',F5S3,'/',S3)

    
    
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)      

P(F=F1|S==S1)= 1 / 4 , P(F=F1|S==S2)= 1 / 3 , P(F=F1|S==S3)= 0 / 3
P(F=F2|S==S1)= 1 / 4 , P(F=F2|S==S2)= 1 / 3 , P(F=F1|S==S3)= 1 / 3
P(F=F3|S==S1)= 0 / 4 , P(F=F3|S==S2)= 1 / 3 , P(F=F1|S==S3)= 1 / 3
P(F=F4|S==S1)= 1 / 4 , P(F=F4|S==S2)= 0 / 3 , P(F=F1|S==S3)= 1 / 3
P(F=F5|S==S1)= 1 / 4 , P(F=F5|S==S2)= 0 / 3 , P(F=F1|S==S3)= 0 / 3


<h3> Q9: Given two sentences S1, S2</h3>
You will be given two sentences S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [20]:
Sentence_1= "the first column F will contain only 5 uniques values"
Sentence_2= "the second column S will contain only 3 uniques values"

def string_features(S1, S2):
    
    #convert the strings into lists using split
    A = S1.split()
    B = S2.split()
    
    #a. Number of common words between S1, S2
    print(len(set(A).intersection(set(B))))
    
    #b. Words in S1 but not in S2
    print(list(set(A)-set(B))) 
    
    #c. Words in S2 but not in S1
    print(list(set(B)-set(A)))
    return

string_features(Sentence_1,Sentence_2)

7
['5', 'first', 'F']
['3', 'S', 'second']


<h3> Q10: Log- loss</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [1]:
import math

def compute_log_loss(A):
    
    #sum_series as 0 initially to store the sum of series in the formulae
    sum_series = 0
    for i in range(len(A)):
        
        #to calculate sum of the series based on above formulae
        sum_series += ((A[i][0] * math.log(A[i][1],10)) + ((1-A[i][0]) * (math.log(1-A[i][1],10))))
    log_loss = ((-1/8)*sum_series) 
    
    return log_loss


A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

compute_log_loss(A)

0.42430993457031635